export {
  api,
  parseApiResponse,
  setAuthToken,
  getApiErrorMessage,
  authAPI,
  kycAPI,
  depositAPI,
  withdrawalAPI,
  marketAPI,
  tradeAPI,
  stakingAPI,
  dashboardAPI,
  walletAPI,
  marketingAPI,
  adminMarketingAPI,
} from '../services/api.js';
